std = "roblox"

[rules]
unused_variable = "allow"
global_usage = "allow"
shadowing = "allow"
multiple_statements = "allow"
unscoped_variables = "allow"
deprecated = "allow"
incorrect_standard_library_use = "allow"